### ISSUE TITLE
Added in the intergration, but no device or entities.

### ISSUE THREAD

**Issue by tzungtzu** [slydiman/ha_custom_onvif#4]
Could use custom onvif in the intergration, and add my ip camera, showed on the intergration, but no device or entities.

core-2021.3.4

Home Assistant Container
On docker NAS.

**Comment by slydiman** [comment]
What is the camera model?

Please enable logging in `configuration.yaml`:
```
logger:
  default: debug
  logs:
    homeassistant.components.onvif: debug
    zeeep.transport: debug
    custom_components.onvif: debug
```
and provide the logs.

Probably something is incompatible with core-2021.3.4 because it is too old.
